const T = {
  STATE_GET_TODO: 'STATE_GET_TODO',
  STATE_GET_TODO_DETAIL: 'STATE_GET_TODO_DETAIL',
  STATE_POST_TODO_TITLE: 'STATE_POST_TODO_TITLE',
  STATE_POST_TODO_DATE: 'STATE_POST_TODO_DATE',
  STATE_POST_TODO_COMMENT: 'STATE_POST_TODO_COMMENT',
  STATE_POST_TODO_PRIORITY: 'STATE_POST_TODO_PRIORITY',
  STATE_POST_TODO: 'STATE_POST_TODO',
  STATE_REMOVE_TODO: 'STATE_REMOVE_TODO',
  STATE_EDIT_TODO: 'STATE_EDIT_TODO',
};

export default T;
